"""What the salon sells and what it charges: the real catalog, services and products.

Stdlib only, and read by BOTH the seeder and the tests — so a change to the dataset cannot leave
the tests asserting against prices the salon does not charge.

The names and the prices are the salon's own and are product data: they stay in Spanish, spelled
and capitalized as the salon writes them, and are not tidied. The people who do the work are
`demo_data.py` and are still invented.

**A service carries two prices, and a NULL is not a zero.** `price_female` or `price_male` set to
None means the salon does not offer that service to that client, which is a refusal with a reason
rather than a fallback to the other column — docs/PROJECT_DEFINITION.md §5. A service priced the
same for everyone carries the same amount in both.

Aliases are only what a specialist would say verbatim, and only where the phrase names ONE row.
Bare "manicura" is deliberately an alias of nothing: three services begin with it at three
prices, so it must come back ambiguous rather than resolve to the cheapest.
"""

from __future__ import annotations

DISCIPLINES: tuple[dict, ...] = (
    {"code": "nails", "name": "Uñas"},
    {"code": "wax", "name": "Depilación"},
)

# --- Services: manicure, pedicure and pintura, priced per client ------------------------------
_MANICURE_PEDICURE: tuple[dict, ...] = (
    {
        "service_ref": "svc-001",
        "name": "Manicura + pintura normal",
        "discipline": "nails",
        "price_female": "300.00",
        "price_male": "400.00",
        "aliases": "manicura con pintura normal|manicura normal",
    },
    {
        "service_ref": "svc-002",
        "name": "Pedicura + pintura normal",
        "discipline": "nails",
        "price_female": "400.00",
        "price_male": "500.00",
        "aliases": "pedicura con pintura normal|pedicura normal",
    },
    {
        "service_ref": "svc-003",
        "name": "Manicura + pintura en gel",
        "discipline": "nails",
        "price_female": "400.00",
        "price_male": "500.00",
        "aliases": "manicura con gel|manicura en gel|manicura gel",
    },
    {
        "service_ref": "svc-004",
        "name": "Pedicura + pintura en gel",
        "discipline": "nails",
        "price_female": "500.00",
        "price_male": "600.00",
        "aliases": "pedicura con gel|pedicura en gel|pedicura gel",
    },
    {
        "service_ref": "svc-005",
        "name": "Manicura VIP",
        "discipline": "nails",
        "price_female": "550.00",
        "price_male": "650.00",
        "aliases": "manicura vip",
    },
    {
        "service_ref": "svc-006",
        "name": "Pedicura VIP",
        "discipline": "nails",
        "price_female": "650.00",
        "price_male": "750.00",
        "aliases": "pedicura vip",
    },
    {
        "service_ref": "svc-007",
        "name": "Pintura normal",
        "discipline": "nails",
        "price_female": "200.00",
        "price_male": "300.00",
        "aliases": "solo pintura normal",
    },
    {
        "service_ref": "svc-008",
        "name": "Pintura gel",
        "discipline": "nails",
        "price_female": "350.00",
        "price_male": "450.00",
        "aliases": "solo pintura gel|pintura en gel",
    },
    {
        "service_ref": "svc-009",
        "name": "Pintura VIP",
        "discipline": "nails",
        "price_female": "350.00",
        "price_male": "450.00",
        "aliases": "solo pintura vip",
    },
    {
        "service_ref": "svc-010",
        "name": "Pedicure Spa",
        "discipline": "nails",
        "price_female": "1200.00",
        "price_male": "1300.00",
        "aliases": "spa|pedicure spa|pedicura spa",
    },
)

# --- Services: acrylic, resin and the add-ons. One price for every client ---------------------
# The source list writes "Retoque" eight times, each meaning the row above it. `services.name` is
# UNIQUE and a bare "retoque" must not resolve to whichever came first, so each is named after its
# parent: "retoque" then comes back ambiguous through catalog._by_overlap and the specialist says
# which, while "retoque de acrílico" narrows to three.
_ACRYLIC: tuple[dict, ...] = (
    {
        "service_ref": "svc-011",
        "name": "Acrílico + pintura normal",
        "discipline": "nails",
        "price_female": "500.00",
        "price_male": "500.00",
        "aliases": "acrilico con pintura normal|acrilico normal",
    },
    {
        "service_ref": "svc-012",
        "name": "Retoque de Acrílico + pintura normal",
        "discipline": "nails",
        "price_female": "400.00",
        "price_male": "400.00",
        "aliases": "retoque de acrilico normal",
    },
    {
        "service_ref": "svc-013",
        "name": "Acrílico + pintura en gel",
        "discipline": "nails",
        "price_female": "600.00",
        "price_male": "600.00",
        "aliases": "acrilico con gel|acrilico en gel",
    },
    {
        "service_ref": "svc-014",
        "name": "Retoque de Acrílico + pintura en gel",
        "discipline": "nails",
        "price_female": "500.00",
        "price_male": "500.00",
        "aliases": "retoque de acrilico en gel",
    },
    {
        "service_ref": "svc-015",
        "name": "Acrílico VIP",
        "discipline": "nails",
        "price_female": "700.00",
        "price_male": "700.00",
        "aliases": "acrilico vip",
    },
    {
        "service_ref": "svc-016",
        "name": "Retoque de Acrílico VIP",
        "discipline": "nails",
        "price_female": "600.00",
        "price_male": "600.00",
        "aliases": "retoque de acrilico vip",
    },
    {
        "service_ref": "svc-017",
        "name": "Resina",
        "discipline": "nails",
        "price_female": "600.00",
        "price_male": "600.00",
        "aliases": "resina normal",
    },
    {
        "service_ref": "svc-018",
        "name": "Retoque de Resina",
        "discipline": "nails",
        "price_female": "500.00",
        "price_male": "500.00",
        "aliases": "retoque de resina normal",
    },
    {
        "service_ref": "svc-019",
        "name": "Resina de colores",
        "discipline": "nails",
        "price_female": "700.00",
        "price_male": "700.00",
        "aliases": "resina de color|resina colores",
    },
    {
        "service_ref": "svc-020",
        "name": "Retoque de Resina de colores",
        "discipline": "nails",
        "price_female": "600.00",
        "price_male": "600.00",
        "aliases": "retoque de resina de color",
    },
    {
        "service_ref": "svc-021",
        "name": "Poligel",
        "discipline": "nails",
        "price_female": "1000.00",
        "price_male": "1000.00",
        "aliases": "poli gel",
    },
    {
        "service_ref": "svc-022",
        "name": "Retoque de Poligel",
        "discipline": "nails",
        "price_female": "900.00",
        "price_male": "900.00",
        "aliases": "retoque de poli gel",
    },
    {
        "service_ref": "svc-023",
        "name": "Efecto espejo",
        "discipline": "nails",
        "price_female": "500.00",
        "price_male": "500.00",
        "aliases": "espejo",
    },
    {
        "service_ref": "svc-024",
        "name": "Efecto gato",
        "discipline": "nails",
        "price_female": "500.00",
        "price_male": "500.00",
        "aliases": "gato|ojo de gato",
    },
    {
        "service_ref": "svc-025",
        "name": "Builder",
        "discipline": "nails",
        "price_female": "1000.00",
        "price_male": "1000.00",
        "aliases": "builder normal",
    },
    {
        "service_ref": "svc-026",
        "name": "Retoque de Builder",
        "discipline": "nails",
        "price_female": "900.00",
        "price_male": "900.00",
        "aliases": "retoque de builder normal",
    },
    {
        "service_ref": "svc-027",
        "name": "Builder VIP",
        "discipline": "nails",
        "price_female": "1200.00",
        "price_male": "1200.00",
        "aliases": "builder vip",
    },
    {
        "service_ref": "svc-028",
        "name": "Retoque de Builder VIP",
        "discipline": "nails",
        "price_female": "1100.00",
        "price_male": "1100.00",
        "aliases": "retoque de builder vip",
    },
    {
        "service_ref": "svc-029",
        "name": "French",
        "discipline": "nails",
        "price_female": "200.00",
        "price_male": "200.00",
        "aliases": "frencito|french tip",
    },
    {
        "service_ref": "svc-030",
        "name": "Retiro de Acrílico",
        "discipline": "nails",
        "price_female": "250.00",
        "price_male": "250.00",
        "aliases": "retirar acrilico|quitar acrilico",
    },
    {
        "service_ref": "svc-031",
        "name": "Retiro de pintura",
        "discipline": "nails",
        "price_female": "100.00",
        "price_male": "100.00",
        "aliases": "retirar pintura|quitar pintura",
    },
    {
        "service_ref": "svc-032",
        "name": "Retiro con Removedor",
        "discipline": "nails",
        "price_female": "150.00",
        "price_male": "150.00",
        "aliases": "removedor|retirar con removedor",
    },
    {
        "service_ref": "svc-033",
        "name": "Largo",
        "discipline": "nails",
        "price_female": "100.00",
        "price_male": "100.00",
        "aliases": "largo extra",
    },
    {
        "service_ref": "svc-034",
        "name": "Forma",
        "discipline": "nails",
        "price_female": "100.00",
        "price_male": "100.00",
        "aliases": "cambio de forma",
    },
    {
        "service_ref": "svc-035",
        "name": "Rebaja",
        "discipline": "nails",
        "price_female": "100.00",
        "price_male": "100.00",
        "aliases": "rebajar",
    },
    {
        "service_ref": "svc-036",
        "name": "Chancleta",
        "discipline": "nails",
        "price_female": "50.00",
        "price_male": "50.00",
        "aliases": "chancletas",
    },
    {
        "service_ref": "svc-037",
        "name": "Uña",
        "discipline": "nails",
        "price_female": "100.00",
        "price_male": "100.00",
        "aliases": "una suelta|una individual",
    },
    {
        "service_ref": "svc-038",
        "name": "Top",
        "discipline": "nails",
        "price_female": "100.00",
        "price_male": "100.00",
        "aliases": "top coat",
    },
    {
        "service_ref": "svc-039",
        "name": "Secante",
        "discipline": "nails",
        "price_female": "100.00",
        "price_male": "100.00",
        "aliases": "secado",
    },
    {
        "service_ref": "svc-040",
        "name": "Veloterapia",
        "discipline": "nails",
        "price_female": "300.00",
        "price_male": "300.00",
        "aliases": "velo|velo terapia",
    },
)

# --- Services: depilación, cejas, tintado and pestañas, priced per client ---------------------
_WAX: tuple[dict, ...] = (
    {
        "service_ref": "svc-041",
        "name": "Depilación cejas",
        "discipline": "wax",
        "price_female": "250.00",
        "price_male": "350.00",
        "aliases": "cejas|depilacion de cejas",
    },
    {
        "service_ref": "svc-042",
        "name": "Tintado",
        "discipline": "wax",
        "price_female": "250.00",
        "price_male": None,
        "aliases": "tinte|tintar",
    },
    {
        "service_ref": "svc-043",
        "name": "Depilación y tintado de cejas",
        "discipline": "wax",
        "price_female": "450.00",
        "price_male": None,
        "aliases": "cejas y tintado|depilacion y tintado",
    },
    {
        "service_ref": "svc-044",
        "name": "Pestañas",
        "discipline": "wax",
        "price_female": "550.00",
        "price_male": None,
        "aliases": "pestanas|extension de pestanas",
    },
    {
        "service_ref": "svc-045",
        "name": "Bozo",
        "discipline": "wax",
        "price_female": "150.00",
        "price_male": "250.00",
        "aliases": "bigote",
    },
    {
        "service_ref": "svc-046",
        "name": "Mentón",
        "discipline": "wax",
        "price_female": "150.00",
        "price_male": "250.00",
        "aliases": "menton|barbilla",
    },
    {
        "service_ref": "svc-047",
        "name": "Axilas",
        "discipline": "wax",
        "price_female": "300.00",
        "price_male": "400.00",
        "aliases": "axila|depilacion de axilas",
    },
    {
        "service_ref": "svc-048",
        "name": "Brasilero normal",
        "discipline": "wax",
        "price_female": "650.00",
        "price_male": None,
        "aliases": "brasilero sencillo",
    },
    {
        "service_ref": "svc-049",
        "name": "Brasilero completo",
        "discipline": "wax",
        "price_female": "750.00",
        "price_male": None,
        "aliases": "brasilero full",
    },
    {
        "service_ref": "svc-050",
        "name": "Piernas completas",
        "discipline": "wax",
        "price_female": "850.00",
        "price_male": "1400.00",
        "aliases": "piernas|piernas enteras",
    },
    {
        "service_ref": "svc-051",
        "name": "Media pierna",
        "discipline": "wax",
        "price_female": "450.00",
        "price_male": "800.00",
        "aliases": "media piernas|mitad de pierna",
    },
    {
        "service_ref": "svc-052",
        "name": "Glúteos",
        "discipline": "wax",
        "price_female": "600.00",
        "price_male": None,
        "aliases": "gluteos|nalgas",
    },
    {
        "service_ref": "svc-053",
        "name": "Barba",
        "discipline": "wax",
        "price_female": None,
        "price_male": "750.00",
        "aliases": "barba completa",
    },
    {
        "service_ref": "svc-054",
        "name": "Pecho",
        "discipline": "wax",
        "price_female": None,
        "price_male": "700.00",
        "aliases": "pectorales",
    },
    {
        "service_ref": "svc-055",
        "name": "Abdomen",
        "discipline": "wax",
        "price_female": "600.00",
        "price_male": "700.00",
        "aliases": "barriga",
    },
    {
        "service_ref": "svc-056",
        "name": "Pecho y Abdomen",
        "discipline": "wax",
        "price_female": None,
        "price_male": "1200.00",
        "aliases": "pecho y barriga",
    },
    {
        "service_ref": "svc-057",
        "name": "Espalda Completa",
        "discipline": "wax",
        "price_female": None,
        "price_male": "1200.00",
        "aliases": "espalda|espalda entera",
    },
)

SERVICES: tuple[dict, ...] = _MANICURE_PEDICURE + _ACRYLIC + _WAX

# --- Products ---------------------------------------------------------------------------------
# No discipline: any specialist may sell a drink, so tools.sell_product runs no discipline check.
# Selling one pays NO commission — docs/PROJECT_DEFINITION.md §7 — which is why a product line
# lives in its own table rather than beside a service line.
#
# `price_specialist` is what she pays when she takes one for herself, and that is a debit against
# her rather than a sale.
PRODUCTS: tuple[dict, ...] = (
    {
        "product_ref": "prd-001",
        "name": "Agua",
        "price_client": "25.00",
        "price_specialist": "15.00",
        "aliases": "agua|botella de agua",
    },
    {
        "product_ref": "prd-002",
        "name": "Presidente",
        "price_client": "150.00",
        "price_specialist": "125.00",
        "aliases": "presidente|cerveza presidente",
    },
    {
        "product_ref": "prd-003",
        "name": "Corona",
        "price_client": "200.00",
        "price_specialist": "175.00",
        "aliases": "corona|cerveza corona",
    },
    {
        "product_ref": "prd-004",
        "name": "Modelo",
        "price_client": "200.00",
        "price_specialist": "150.00",
        "aliases": "modelo|cerveza modelo",
    },
    {
        "product_ref": "prd-005",
        "name": "Malta",
        "price_client": "50.00",
        "price_specialist": "40.00",
        "aliases": "malta|maltita",
    },
    {
        "product_ref": "prd-006",
        "name": "Sprite",
        "price_client": "50.00",
        "price_specialist": "40.00",
        "aliases": "sprite",
    },
    {
        "product_ref": "prd-007",
        "name": "Coca-Cola",
        "price_client": "50.00",
        "price_specialist": "40.00",
        "aliases": "coca cola|coca|cocacola|refresco de cola",
    },
    {
        "product_ref": "prd-008",
        "name": "Doritos",
        "price_client": "50.00",
        "price_specialist": "40.00",
        "aliases": "papitas doritos",
    },
    {
        "product_ref": "prd-009",
        "name": "Lays",
        "price_client": "50.00",
        "price_specialist": "40.00",
        "aliases": "lays|papitas lays",
    },
    {
        "product_ref": "prd-010",
        "name": "Oreo",
        "price_client": "35.00",
        "price_specialist": "25.00",
        "aliases": "oreo|galleta oreo",
    },
    {
        "product_ref": "prd-011",
        "name": "Ritz",
        "price_client": "35.00",
        "price_specialist": "25.00",
        "aliases": "ritz|galleta ritz",
    },
    {
        "product_ref": "prd-012",
        "name": "Gatorade",
        "price_client": "60.00",
        "price_specialist": "50.00",
        "aliases": "gatorade|gatoreid",
    },
    {
        "product_ref": "prd-013",
        "name": "Wafer",
        "price_client": "25.00",
        "price_specialist": "15.00",
        "aliases": "wafer|waffer",
    },
    {
        "product_ref": "prd-014",
        "name": "Jugo de Naranja",
        "price_client": "50.00",
        "price_specialist": "40.00",
        "aliases": "jugo de naranja|jugo|naranja",
    },
    {
        "product_ref": "prd-015",
        "name": "Barras Protéicas",
        "price_client": "65.00",
        "price_specialist": "55.00",
        "aliases": "barra proteica|barras proteicas|barrita",
    },
    {
        "product_ref": "prd-017",
        "name": "Ruffles",
        "price_client": "50.00",
        "price_specialist": "40.00",
        "aliases": "ruffles",
    },
    {
        "product_ref": "prd-018",
        "name": "Trident Menta",
        "price_client": "15.00",
        "price_specialist": "10.00",
        "aliases": "trident menta|chicle de menta",
    },
    {
        "product_ref": "prd-019",
        "name": "Trident Fresa",
        "price_client": "15.00",
        "price_specialist": "10.00",
        "aliases": "trident fresa",
    },
    {
        "product_ref": "prd-020",
        "name": "Trident Fresa/Limón",
        "price_client": "50.00",
        "price_specialist": "40.00",
        "aliases": "trident fresa limon",
    },
    {
        "product_ref": "prd-021",
        "name": "Mini Chokis",
        "price_client": "75.00",
        "price_specialist": "65.00",
        "aliases": "mini chokis",
    },
    {
        "product_ref": "prd-022",
        "name": "Maní con Limón",
        "price_client": "25.00",
        "price_specialist": "20.00",
        "aliases": "mani con limon",
    },
    {
        "product_ref": "prd-023",
        "name": "Maní con Sal",
        "price_client": "25.00",
        "price_specialist": "20.00",
        "aliases": "mani con sal",
    },
    {
        "product_ref": "prd-024",
        "name": "Maní MIX",
        "price_client": "25.00",
        "price_specialist": "20.00",
        "aliases": "mani mix",
    },
    {
        "product_ref": "prd-025",
        "name": "Emperador",
        "price_client": "35.00",
        "price_specialist": "30.00",
        "aliases": "emperador",
    },
    {
        "product_ref": "prd-026",
        "name": "Hojuelitas BBQ",
        "price_client": "30.00",
        "price_specialist": "25.00",
        "aliases": "hojuelitas|hojuelitas bbq",
    },
    {
        "product_ref": "prd-028",
        "name": "Bolón",
        "price_client": "15.00",
        "price_specialist": "10.00",
        "aliases": "bolon",
    },
    {
        "product_ref": "prd-030",
        "name": "Chokis",
        "price_client": "100.00",
        "price_specialist": "80.00",
        "aliases": "chokis",
    },
    {
        "product_ref": "prd-032",
        "name": "Cheetos",
        "price_client": "25.00",
        "price_specialist": "15.00",
        "aliases": "cheetos",
    },
    {
        "product_ref": "prd-033",
        "name": "Platanitos",
        "price_client": "35.00",
        "price_specialist": "30.00",
        "aliases": "platanitos",
    },
    {
        "product_ref": "prd-034",
        "name": "Chicharron",
        "price_client": "30.00",
        "price_specialist": "25.00",
        "aliases": "chicharron",
    },
    {
        "product_ref": "prd-035",
        "name": "Mini Crackets",
        "price_client": "75.00",
        "price_specialist": "60.00",
        "aliases": "mini crackets|crackets",
    },
    {
        "product_ref": "prd-036",
        "name": "Doritos Dinamita",
        "price_client": "35.00",
        "price_specialist": "25.00",
        "aliases": "doritos dinamita|dinamita",
    },
    {
        "product_ref": "prd-037",
        "name": "Mamut",
        "price_client": "35.00",
        "price_specialist": "30.00",
        "aliases": "mamut",
    },
    {
        "product_ref": "prd-038",
        "name": "Dino Fresa",
        "price_client": "25.00",
        "price_specialist": "20.00",
        "aliases": "dino fresa|dino",
    },
    {
        "product_ref": "prd-039",
        "name": "MilkyWay",
        "price_client": "35.00",
        "price_specialist": "30.00",
        "aliases": "milkyway|milky way",
    },
    {
        "product_ref": "prd-040",
        "name": "M&M",
        "price_client": "35.00",
        "price_specialist": "30.00",
        "aliases": "m&m|eme y eme",
    },
    {
        "product_ref": "prd-041",
        "name": "Mentas",
        "price_client": "2.50",
        "price_specialist": "2.50",
        "aliases": "menta|mentas",
    },
    {
        "product_ref": "prd-042",
        "name": "Trolli",
        "price_client": "150.00",
        "price_specialist": "125.00",
        "aliases": "trolli|gomitas",
    },
    {
        "product_ref": "prd-043",
        "name": "Maduritos",
        "price_client": "25.00",
        "price_specialist": "20.00",
        "aliases": "maduritos",
    },
)
