"""Which price column a client's name selects, decided without a model.

Stdlib plus the accent fold. No model and no database, and that is the point rather than a
convenience: `catalog.py` holds that a price is never a model output, and choosing between
RD$850 and RD$1,400 is choosing the price — docs/PROJECT_DEFINITION.md §5.

**Three provenances, not two.** A name found in a table is not the same claim as a name nobody
recognized. `MATCHED` is a lookup that succeeded; `DEFAULTED` is the female column applied because
the name is unknown or genuinely goes both ways; `STATED` is the specialist saying so outright,
which always wins. Only `DEFAULTED` earns the notice on the ticket, so "Laura" reads clean and
"Ariel" asks to be checked.

The tables are common given names in the Dominican Republic and are **not exhaustive** — they
cannot be. That is what `DEFAULTED` and the visible notice are for: an unrecognized name is
priced female and said out loud, never priced female in silence.

The names are the module's subject rather than its vocabulary, which is why they are in Spanish
while everything around them is English.
"""

from __future__ import annotations

from conversation_core import fold

#: How a sale came to carry the client it carries.
STATED = "stated"
MATCHED = "matched"
DEFAULTED = "defaulted"

_FEMALE_NAMES = (
    "María",
    "Ana",
    "Rosa",
    "Carmen",
    "Juana",
    "Altagracia",
    "Yamilé",
    "Carla",
    "Laura",
    "Sofía",
    "Isabel",
    "Luisa",
    "Marta",
    "Elena",
    "Patricia",
    "Yolanda",
    "Mercedes",
    "Dulce",
    "Nery",
    "Yaritza",
    "Yanet",
    "Massiel",
    "Katherine",
    "Kenia",
    "Wendy",
    "Dahiana",
    "Yuderka",
    "Scarlet",
    "Yocasta",
    "Ramona",
    "Francisca",
    "Josefina",
    "Milagros",
    "Esperanza",
    "Cristina",
    "Claudia",
    "Paola",
    "Andrea",
    "Gabriela",
    "Valentina",
    "Camila",
    "Daniela",
    "Alejandra",
    "Verónica",
    "Mónica",
    "Diana",
    "Lucía",
    "Marina",
    "Teresa",
    "Julia",
    "Emilia",
    "Adriana",
    "Fabiola",
    "Ivelisse",
    "Nurys",
    "Solanyi",
    "Yohanna",
    "Perla",
    "Belkis",
    "Miguelina",
    "Nidia",
    "Awilda",
    "Clara",
    "Delia",
    "Elsa",
    "Eva",
    "Gladys",
    "Hilda",
    "Iris",
    "Lourdes",
    "Magdalena",
    "Marisol",
    "Nancy",
    "Norma",
    "Olga",
    "Rafaela",
    "Sandra",
    "Silvia",
    "Virginia",
    "Xiomara",
    "Zoila",
    "Yaneris",
    "Rosanna",
    "Génesis",
    "Ashley",
    "Emely",
    "Nicole",
    "Michelle",
    "Stephanie",
    "Yeimy",
    "Leidy",
    "Karina",
    "Katiuska",
    "Maribel",
    "Migdalia",
    "Rossy",
    "Yudelka",
    "Yanira",
    "Arisleyda",
    "Deisy",
    "Elizabeth",
    "Esmeralda",
    "Ingrid",
    "Jacqueline",
    "Jennifer",
    "Johanna",
    "Karla",
    "Lissette",
    "Marlene",
    "Nathalie",
    "Noelia",
    "Odalis",
    "Yeni",
    "Ángela",
    "Beatriz",
    "Catalina",
    "Doris",
    "Estela",
    "Fátima",
    "Gisela",
    "Inés",
    "Leonor",
    "Lidia",
    "Mariela",
    "Nereida",
    "Petronila",
    "Yisel",
    "Yuleisy",
)

_MALE_NAMES = (
    "José",
    "Juan",
    "Pedro",
    "Luis",
    "Carlos",
    "Miguel",
    "Rafael",
    "Manuel",
    "Francisco",
    "Ramón",
    "Antonio",
    "Jesús",
    "Domingo",
    "Santiago",
    "Andrés",
    "Fernando",
    "Roberto",
    "Ricardo",
    "Eduardo",
    "Jorge",
    "Julio",
    "Víctor",
    "Héctor",
    "Alberto",
    "Alfredo",
    "Ángel",
    "Arturo",
    "Bienvenido",
    "César",
    "Cristian",
    "Daniel",
    "David",
    "Diego",
    "Edwin",
    "Elvis",
    "Emilio",
    "Enrique",
    "Ernesto",
    "Esteban",
    "Federico",
    "Felipe",
    "Félix",
    "Gabriel",
    "Genaro",
    "Gerardo",
    "Gregorio",
    "Guillermo",
    "Gustavo",
    "Ignacio",
    "Isidro",
    "Iván",
    "Javier",
    "Joaquín",
    "Johnny",
    "Jonathan",
    "Josué",
    "Kelvin",
    "Leonardo",
    "Lorenzo",
    "Marcos",
    "Mario",
    "Martín",
    "Mauricio",
    "Nelson",
    "Nicolás",
    "Norberto",
    "Octavio",
    "Omar",
    "Óscar",
    "Pablo",
    "Patricio",
    "Ramiro",
    "Raúl",
    "Reinaldo",
    "René",
    "Rodolfo",
    "Rogelio",
    "Rubén",
    "Salvador",
    "Samuel",
    "Sebastián",
    "Sergio",
    "Simón",
    "Teodoro",
    "Tomás",
    "Wilfredo",
    "Wilson",
    "Yunior",
    "Starling",
    "Franklin",
    "Radhamés",
    "Ambiorix",
    "Jefferson",
    "Randy",
    "Alexander",
    "Anderson",
    "Brayan",
    "Christopher",
    "Eddy",
    "Erick",
    "Frank",
    "Fredy",
    "Hansel",
    "Jeison",
    "Kevin",
    "Leandro",
    "Maikol",
    "Michael",
    "Robinson",
    "Wander",
    "Yeison",
    "Yoel",
    "Adalberto",
    "Amaury",
    "Aníbal",
    "Benito",
    "Confesor",
    "Eladio",
    "Fausto",
    "Hipólito",
    "Leonel",
    "Máximo",
    "Winston",
)

#: Names that genuinely go both ways here. Listed so they DEFAULT rather than matching whichever
#: table happened to hold them — the notice on the ticket is the whole reason to know the
#: difference.
_AMBIGUOUS_NAMES = (
    "Ariel",
    "Alexis",
    "Yuri",
    "Cruz",
    "Guadalupe",
    "Trinidad",
    "Rosario",
    "Sandy",
    "Yordani",
    "Yeral",
    "Yamil",
    "Amparo",
    "Reyes",
    "Yan",
    "Yeri",
)

_FEMALE = frozenset(fold(n) for n in _FEMALE_NAMES)
_MALE = frozenset(fold(n) for n in _MALE_NAMES)
_AMBIGUOUS = frozenset(fold(n) for n in _AMBIGUOUS_NAMES)


def given_name(client_name: str) -> str:
    """The folded first token of `client_name`, which is what the tables are keyed on.

    A compound resolves on its first part deliberately: "María José" is a woman and "José María"
    is a man, and taking the first token is what gets both right.
    """
    return fold(client_name or "").split(" ")[0] if (client_name or "").strip() else ""


def derive(client_name: str) -> tuple[str, str]:
    """`(gender, provenance)` for this client, defaulting female and saying when it did."""
    first = given_name(client_name)
    if first and first not in _AMBIGUOUS:
        if first in _FEMALE:
            return "female", MATCHED
        if first in _MALE:
            return "male", MATCHED
    return "female", DEFAULTED
